version: '3'

services:
  db:
    image: postgres:14.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: anylist-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
